In [4]:
import torch
import torch.nn.functional as F

h_hat, h_ture = torch.randn(2, 3, 4, 2), torch.randn(2, 3, 4, 2)

In [ ]:
H = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [0, 0, 0 ,0]])
H.shape

torch.Size([2, 4])

In [ ]:
H = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [3, 1, -1 ,-3]])
print(H)
Hfft = torch.fft.fft(H, dim=0)
print(Hfft)
print(torch.fft.ifft(Hfft, dim=0))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 3,  1, -1, -3]])
tensor([[ 9.0000+0.0000j,  9.0000+0.0000j,  9.0000+0.0000j,  9.0000+0.0000j],
        [-3.0000-1.7321j, -1.5000-4.3301j,  0.0000-6.9282j,  1.5000-9.5263j],
        [-3.0000+1.7321j, -1.5000+4.3301j,  0.0000+6.9282j,  1.5000+9.5263j]])
tensor([[ 1.0000+0.j,  2.0000+0.j,  3.0000+0.j,  4.0000+0.j],
        [ 5.0000+0.j,  6.0000+0.j,  7.0000+0.j,  8.0000+0.j],
        [ 3.0000+0.j,  1.0000+0.j, -1.0000+0.j, -3.0000+0.j]])


: 

In [8]:
Hfft = torch.fft.fft(H, dim=1)
Hfft

tensor([[10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j],
        [26.+0.j, -2.+2.j, -2.+0.j, -2.-2.j]])

In [9]:
Hfft = torch.fft.ifft(H, dim=0)
Hfft

tensor([[ 3.-0.j,  4.-0.j,  5.-0.j,  6.-0.j],
        [-2.-0.j, -2.-0.j, -2.-0.j, -2.-0.j]])

In [5]:
def fft_nmse(h_hat, h_ture):
      
    _, f, _, _ = h_ture.shape
    _, fm, _, _ = h_hat.shape

    pad_total = f - fm
    # pad = [rx_left, rx_right, tx_left, tx_right, f1_left, f1_right]
    pad_values = [0, 0, 0, 0, 0, pad_total]

    h_hat = F.pad(h_hat, pad=pad_values, mode='constant', value=0.0)
    print(h_hat.shape, h_ture.shape, h_ture,h_hat, sep='\n')

    # nmse = nmse(h_hat=h_hat, h_true=h_true)
    
    # retrun nmse
fft_nmse(h_hat, h_ture)


torch.Size([2, 3, 4, 2])
torch.Size([2, 3, 4, 2])
tensor([[[[ 0.3018,  0.5400],
          [-1.3600, -1.6019],
          [ 1.8516,  0.2872],
          [ 0.4144,  1.3692]],

         [[-0.3145, -1.7416],
          [-0.4043, -2.2727],
          [ 0.6450, -0.3968],
          [ 0.8201, -0.6230]],

         [[ 0.6813, -1.1592],
          [ 0.9295, -0.6778],
          [ 0.2237,  0.0103],
          [-3.2479, -0.4156]]],


        [[[ 0.6484, -0.9893],
          [ 0.7801, -0.5235],
          [ 0.1996,  0.2828],
          [ 1.2764,  0.2394]],

         [[-0.1867,  0.5812],
          [-0.9084,  0.3200],
          [-0.7195,  1.0448],
          [ 1.9578,  1.5735]],

         [[-1.2516,  0.9552],
          [ 1.4446,  0.3822],
          [ 1.0533,  0.5175],
          [ 1.8115,  0.8874]]]])
tensor([[[[-1.4992, -0.8887],
          [ 0.2336,  1.6050],
          [ 0.7740, -0.2017],
          [ 2.4617,  2.2014]],

         [[ 0.0125, -0.3128],
          [-0.1418, -1.0884],
          [ 0.1671,  0.0624],
   

In [ ]:
import numpy as np
import torch

A = torch.rand(2, 3264, 514, 1, dtype=torch.complex64)
At = torch.fft.fft(A, dim=1)
print("At.shape", At.shape, "A.shape", A.shape)
print("At.dtype", At.dtype, "A.dtype", A.dtype)
# ydim, hdim = (1, 2), (1, 2, 3)
Am1 = torch.mean(A, dim=1, keepdim=True)
Am2 = torch.mean(A, dim=(1,3), keepdim=True)
print("Am1.shape", Am1.shape, "Am2.shape", Am2.shape)

At.shape torch.Size([2, 3264, 514, 1]) A.shape torch.Size([2, 3264, 514, 1])
At.dtype torch.complex64 A.dtype torch.complex64
Am1.shape torch.Size([2, 1, 514, 1]) Am2.shape torch.Size([2, 1, 514, 1])


In [7]:
A = torch.rand(2, 3264, 256, 1, dtype=torch.complex64)
At = torch.fft.fft2(A, dim=1)
print("At.shape", At.shape, "A.shape", A.shape)
print("At.dtype", At.dtype, "A.dtype", A.dtype)
# ydim, hdim = (1, 2), (1, 2, 3)
Am1 = torch.mean(A, dim=1, keepdim=True)
Am2 = torch.mean(A, dim=(1,3), keepdim=True)
print("Am1.shape", Am1.shape, "Am2.shape", Am2.shape)

At.shape torch.Size([2, 3264, 256, 1]) A.shape torch.Size([2, 3264, 256, 1])
At.dtype torch.complex64 A.dtype torch.complex64
Am1.shape torch.Size([2, 1, 256, 1]) Am2.shape torch.Size([2, 1, 256, 1])


In [15]:
A = torch.rand(2, 3264, 256, 1, dtype=torch.complex64)
A1 = torch.fft.fft(A, dim=1)
A2 = torch.fft.fft2(A, dim=1)
Ae = A1-A2
torch.equal(A1,A2)

True

In [14]:
A = torch.rand(2, 3264, 256, 1, dtype=torch.complex64)
A1 = torch.fft.ifft(A, dim=1)
A2 = torch.fft.ifft2(A, dim=1)
Ae = A1-A2
torch.equal(A1,A2)

True

In [5]:
Y = torch.randint(0, 2, size=(2, 3, 4, 1)).float()
mean = Y.mean(dim=(1, 3), keepdim=True)
print(Y)
print('-' * 40)
print(mean)

mean = Y.mean(dim=(1, ), keepdim=True)
print('-' * 40)
print(mean)

tensor([[[[1.],
          [0.],
          [0.],
          [1.]],

         [[0.],
          [0.],
          [0.],
          [1.]],

         [[1.],
          [1.],
          [0.],
          [0.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[0.],
          [1.],
          [0.],
          [0.]],

         [[1.],
          [1.],
          [1.],
          [0.]]]])
----------------------------------------
tensor([[[[0.6667],
          [0.3333],
          [0.0000],
          [0.6667]]],


        [[[0.6667],
          [1.0000],
          [0.6667],
          [0.3333]]]])
----------------------------------------
tensor([[[[0.6667],
          [0.3333],
          [0.0000],
          [0.6667]]],


        [[[0.6667],
          [1.0000],
          [0.6667],
          [0.3333]]]])


In [38]:
import torch
import torch.nn as nn

def normalize(x, dim):
    mean = torch.mean(x, dim=dim, keepdim=True)
    std = torch.std(x, dim=dim, keepdim=True)
    return (x - mean) / std

def normalize_data(Y, H, real_imag_sep=True):
    """Normalize data per sample: if real_imag_sep=True, normalize real and imaginary parts
    of Y,H separately then concatenate, otherwise concatenate real and imaginary parts first
    then normalize.If Y is a 5D tensor (ue,t,f,rx,tx), embed time t and frequency f positional
    information into the returned Y.
    
    Parameters:
        Y (torch.Tensor): Complex-valued input data, shape=(ue,t,f,rx,tx) or (ue,tf,rx,tx).

        H (torch.Tensor): Complex-valued reference data, shape=(ue,f',rx,tx).

        real_imag_sep (bool): Whether to normalize real and imaginary parts separately.
        
    Returns:
        tuple: (Y, H)
            - Y (torch.Tensor): Normalized input data, shape=(ue,t*f,2*rx*tx) or (ue,t*f,2*rx*tx+2) if 5D input.
            
            - H (torch.Tensor): Normalized reference data, shape=(ue,f',2*rx,tx).
"""

    y_shape = list(Y.shape) # (ue, 3264, 256, 1) or (ue, 17, 192, 256, 1)
    h_shape = list(H.shape) # (ue, 3264, 256, 1)

    if len(y_shape) == 5:   
        ue, t, f, rx, tx = y_shape
        Y = Y.reshape(ue, t*f, rx*tx)

    if len(y_shape) == 4:   
        ue, tf, rx, tx = y_shape
        Y = Y.reshape(ue, tf, rx*tx)
    ydim, hdim = (1, 2), (1, 2, 3)

    if real_imag_sep:
        # Normalize real and imaginary parts separately
        Yr, Yi = normalize(Y.real.float(), dim=ydim), normalize(Y.imag.float(), dim=ydim)
        Hr, Hi = normalize(H.real.float(), dim=hdim), normalize(H.imag.float(), dim=hdim)
        Y = torch.cat([Yr, Yi], dim=-1)
        H = torch.cat([Hr, Hi], dim=-2)
    else:
        Yr, Yi = Y.real.float(), Y.imag.float()
        Hr, Hi = H.real.float(), H.imag.float()
        Y = torch.cat([Yr, Yi], dim=-1)
        H = torch.cat([Hr, Hi], dim=-2)
        Y = normalize(Y, dim=ydim)
        H = normalize(H, dim=hdim)
    
    if len(y_shape) == 5:
        ## 把 时间、频率的信息嵌入到 Y 中
        ue, t, f, rx, tx = y_shape
        t_marker = torch.arange(t, device=Yr.device, dtype=Yr.dtype)
        t_marker = (t_marker - t_marker.mean()) / t_marker.std()
        t_marker = t_marker.repeat_interleave(f)  # 形状: (t*f,)
        t_marker = t_marker.view(1, t*f, 1)  # 形状: (1, t*f, 1)
        t_marker = t_marker.expand(ue, t*f, 1)  # 形状: (ue, t*f, 1)
        
        # 创建f位置标记：对于t个循环，每个循环包含0到f-1
        f_marker = torch.arange(f, device=Yr.device, dtype=Yr.dtype)
        f_marker = (f_marker - f_marker.mean()) / f_marker.std()
        f_marker = f_marker.repeat(t)  # 形状: (t*f,)
        f_marker = f_marker.view(1, t*f, 1)  # 形状: (1, t*f, 1)
        f_marker = f_marker.expand(ue, t*f, 1)  # 形状: (ue, t*f, 1)

        Y = torch.cat([Y, t_marker, f_marker], dim=-1)

    return Y, H

In [ ]:
Y = torch.rand(2, 17, 192, 256,1) + 1j*torch.rand(2, 17, 192, 256,1)
H = torch.rand(2, 3264, 256,1) + 1j*torch.rand(2, 3264, 256,1)
Y0, H0 = normalize_data(Y, H, real_imag_sep=True)
print(Y0.shape, H0.shape)
Y0, H0 = normalize_data(Y, H, real_imag_sep=False)
print(Y0.shape, H0.shape)

torch.Size([2, 3264, 514]) torch.Size([2, 3264, 512, 1])
torch.Size([2, 3264, 514]) torch.Size([2, 3264, 512, 1])


In [ ]:
Y = torch.rand(2, 2, 3, 2, 1) + 1j*torch.rand(2, 2, 3, 2, 1)
H = torch.rand(2, 6, 2, 1) + 1j*torch.rand(2, 6, 2, 1)
Y0, H0 = normalize_data(Y / 100, H, real_imag_sep=True)
print(Y0.shape, H0.shape)
Y0, H0 = normalize_data(Y, H, real_imag_sep=False)
print(Y0.shape, H0.shape)

torch.Size([2, 6, 6]) torch.Size([2, 6, 4, 1])
torch.Size([2, 6, 6]) torch.Size([2, 6, 4, 1])


In [47]:
A = torch.rand(2,3,4)
torch.std(A, dim=(1,2)), torch.var(A, dim=(1,2)), torch.sqrt(torch.var(A, dim=(1,2)))

(tensor([0.2897, 0.3651]), tensor([0.0839, 0.1333]), tensor([0.2897, 0.3651]))

In [ ]:
ue, t, f, rx = 2, 3, 4, 2
A = torch.randint(0, 10, (ue, t, f, rx))
print(A)

# B = A.reshape(ue, t, f, rx*tx)

# print(B)

C = A.reshape(ue, t*f,-1)
print(C)

In [ ]:
t_marker = torch.arange(t).float()
t_marker = (t_marker - t_marker.mean()) / t_marker.std()
t_marker = t_marker.repeat_interleave(f)  # 形状: (t*f,)
t_marker = t_marker.view(1, t*f, 1)  # 形状: (1, t*f, 1)
t_marker = t_marker.expand(ue, t*f, 1)  # 形状: (ue, t*f, 1)

# 创建f位置标记：对于t个循环，每个循环包含0到f-1
f_marker = torch.arange(f).float()
f_marker = (f_marker - f_marker.mean()) / f_marker.std()
f_marker = f_marker.repeat(t)  # 形状: (t*f,)
f_marker = f_marker.view(1, t*f, 1)  # 形状: (1, t*f, 1)
f_marker = f_marker.expand(ue, t*f, 1)  # 形状: (ue, t*f, 1)

In [ ]:
D = torch.cat([C, t_marker, f_marker], dim=-1)
print(D.shape)
print(D)

In [ ]:
t_marker = torch.arange(f, device=A.device, dtype=torch.float32)
print(t_marker)
t_marker = (t_marker - t_marker.mean()) / t_marker.std()
print(t_marker)
t_marker = t_marker.repeat_interleave(t)  # 形状: (t*f,)
print(t_marker)
t_marker = t_marker.view(1, t*f, 1)  # 形状: (1, t*f, 1)
print(t_marker)
t_marker = t_marker.expand(ue, t*f, 1)  # 形状: (ue, t*f, 1)
print(t_marker)

In [ ]:
s = A.shape
s

In [ ]:
s = list(A.shape)
s

In [ ]:
s[1:]