In [3]:
from fealpy.backend import bm

# Rayleigh SISO channel (flat fading)
h = (bm.random.randn() + 1j*bm.random.randn()) / bm.sqrt(2)
print("Rayleigh SISO channel h:", h)


Rayleigh SISO channel h: (0.5463877538745284-0.7780043332781346j)


In [4]:
bm.mean(bm.abs(h)**2)

0.903830320183607

In [5]:
L = 5
tau_rms = 1.0
P = bm.exp(-bm.arange(L)/tau_rms)
P = P / bm.sum(P)

h = (bm.random.randn(L) + 1j*bm.random.randn(L)) * bm.sqrt(P/2)


In [6]:
h

array([-0.36464537-0.90233046j, -0.2016631 +0.02747366j,
       -0.03420144-0.04553805j, -0.00784486-0.14996739j,
        0.0120257 -0.03726621j])

In [7]:
P

array([0.63640865, 0.23412166, 0.08612854, 0.03168492, 0.01165623])

In [8]:
P.sum()

1.0

In [10]:
1/256/3264

1.1967677696078431e-06

In [13]:
import numpy as np  
N = 64
H = np.fft.fft(h, N)


In [14]:
from fealpy.sparse import coo_matrix, csr_matrix
from fealpy.backend import bm
I = bm.array([0, 0, 3, 1, 0])
J = bm.array([1, 1, 3, 1, 3])
K = bm.array([2, 3, 3, 1, 2])

V = bm.array([[4, 2, 5, 7, 9],
              [1, 3, 8, 4, 6]])

# A1 = coo_matrix((V, (I, J, K)), shape=(4, 4, 4))
A2 = coo_matrix((None, (I, J, K)), shape=(4, 4, 4))
B = coo_matrix((V, (I, J, K)), shape=(4, 4, 4))

# print(A1.toarray())
print(type(A2), type(B))
print(A2.toarray())
print(B.toarray())

<class 'fealpy.sparse.coo_tensor.COOTensor'> <class 'fealpy.sparse.coo_tensor.COOTensor'>
[[[0. 0. 0. 0.]
  [0. 0. 1. 1.]
  [0. 0. 0. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 1.]]]
[[[[0 0 0 0]
   [0 0 4 2]
   [0 0 0 0]
   [0 0 9 0]]

  [[0 0 0 0]
   [0 7 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]
   [0 0 0 5]]]


 [[[0 0 0 0]
   [0 0 1 3]
   [0 0 0 0]
   [0 0 6 0]]

  [[0 0 0 0]
   [0 4 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]
   [0 0 0 8]]]]


In [8]:
import scipy.sparse as sp

# 创建一个 3x4 的全零 CSR 稀疏矩阵
shape = (3, 4, 3)
empty_matrix_csr = sp.csr_matrix(shape, dtype=float)
empty_matrix_csc = sp.csc_matrix(shape)


ValueError: unable to infer matrix dimensions

In [1]:
import numpy as np
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)
C= A+B

In [2]:
import torch 
A = torch.rand(4, 4)
B = torch.rand(4, 4)
C = A + B

In [3]:
from fealpy.backend import bm
bm.set_backend('numpy')
A = bm.random.rand(4, 4)
B = bm.random.rand(4, 4)
C = A + B
print(type(C))

<class 'numpy.ndarray'>


In [ ]:
from fealpy.backend import bm
from fealpy.utils import timer
devicev = 'cpu'
bm.set_default_device(devicev)
bm.tensor( [1,2,3] ,device= devicev)
tmr = timer()
next(tmr)
tmr.send("A,B")
bm.set_backend('pytorch')
A = bm.random.rand(4, 3264,3264)
B = bm.random.rand(4, 3264,3264)
# tmr.send("A+B")
C = A + B

print(type(C))

<class 'torch.Tensor'>


In [ ]:
import scipy.sparse as sp
import torch
A = torch.zeros((3, 4))
a = sp.csr_matrix((3, 4))
A + a.toarray()


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [ ]:
import numpy as np
A = np.zeros((3, 4))
a = sp.csr_matrix((3, 4))
A + a.toarray()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a.toarray()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
from fealpy.sparse import  csr_matrix
bm.set_backend('pytorch')
A = bm.zeros((3, 4))
a = csr_matrix((3, 4))
A + a.toarray()



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])